version: '2'
services:
    simlife-app:
        image: registry.insight-centre.org/iot-unit/activage-hypothesis-testing
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://simlife-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=simlife
            - SIMLIFE_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    simlife-mongodb:
        extends:
            file: mongodb.yml
            service: simlife-mongodb
